### ISSUE TITLE
Add RSpec tests for calendar controller

### ISSUE THREAD

**Issue by brittanykohler** [brittanykohler/RailsCalendar#2]

**Comment by emgord** [comment]
I can help with this!

**Comment by brittanykohler** [comment]
Thanks Emily!

**Comment by emgord** [comment]
I just started working on this, and I can't figure out where the calendar controller is used. Right now it only has a show method which creates a @date instance variable, but there are no views or model for calendar so I am not sure how it fits in.

**Comment by brittanykohler** [comment]
You're completely right... this isn't being used at all. I ended up using
the events controller. Sorry for the confusion! No RSpec needed for this
one.
