### ISSUE TITLE
Add RSpec tests for events controller

### ISSUE THREAD

**Issue by brittanykohler** [brittanykohler/RailsCalendar#3]

**Comment by hougland** [comment]
I can do this!

**Comment by brittanykohler** [comment]
Thanks Ricky! I just assigned the task to you (rspec has been added to the project).

**Comment by hougland** [comment]
hey! in the events controller, what does this line do? `session[:return_to] = request.referer`

**Comment by hougland** [comment]
Finished!
though I'd still love to hear about request.referrer :)

**Comment by brittanykohler** [comment]
Thanks Ricky! the `session[:return_to] = request.referer` stores the path of the last page the user was at, which is then used in the update method to redirect the user to the page they were on before editing the event. It's similar to `redirect_to :back`, except that it redirects to the page before the last page (back two pages). It would make more sense to use this if I had the edit link on multiple pages, so the user would always go back to the page that they clicked the edit link from. Let me know if that doesn't make sense, and we can chat more! :)
