### ISSUE TITLE
Add RSpec tests for users controller

### ISSUE THREAD

**Issue by brittanykohler** [brittanykohler/RailsCalendar#4]

**Comment by emgord** [comment]
As long as I am doing Rspec I might as well help with this also...

**Comment by brittanykohler** [comment]
Thanks so much! I added you as a collaborator.

**Comment by emgord** [comment]
Okay I have one more question. I am noticing that as you made the transition to user authentication, users can still edit or delete other users by hard coding in the url. For the tests I am going to assume that users should only be able to edit or delete their own stuff, and I can also change the code in the controller to make that work, but just wanted to double check with you first in case you are already working on that.

**Comment by brittanykohler** [comment]
Thanks for checking, Emily! You're right, I haven't fully finished all of
the user authentication functionality. It's on my list of things to do, but
I haven't started that part yet-- if you're already doing it, please
continue! If not, please assume I'm going to add it :)

**Comment by emgord** [comment]
Sounds good, I'll start by writing the tests to do what I think they should first, and then likely will work on the controller to make it all work.
